services:
  - type: web
    name: cinephoria-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run prod
    envVars:
      - key: PORT
        value: 5000
      - key: MONGODB_URI
      - key: DATABASE_URL
      - key: JWT_SECRET
      - key: MYSQL_HOST
